# Site settings
title: Nancy chauhan
description: Learner 
email: nancychn1@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nancy-chauhan.github.io" # the base hostname & protocol for your site, e.g. http://example.com

assets_version: 1

twitter:
  username: nancy_nano_
github:
  username: Nancy-Chauhan
linkedin:
  username: Nancy Chauhan

social:
  name: Nancy Chauhan

lang: en_IN

google_analytics: 'UA-73363098-1'
# Build settings
markdown: kramdown

paginate: 6
paginate_path: "/blog/:num/"
permalink: pretty

feed:
  path: /feed/atom.xml

author:
  name: 'Nancy Chauhan'
  twitter: nancy_nano_

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - vendor
